1- Write a Python Program to Add Two Matrices?

---------------

ANSWER



In [25]:
mat1 = [[1,2],
        [3,4]]
mat2 = [[5,6],
        [7,8]]

In [26]:
def add_mat(mat1,mat2):
    return [[mat1[i][j] + mat2[i][j] for j in range(len(mat1[0]))] for i in range(len(mat1))]

In [34]:
np.add(mat1,mat2)

array([[ 6,  8],
       [10, 12]])

In [27]:
add_mat(mat1,mat2)

[[6, 8], [10, 12]]

2- Write a Python Program to Multiply Two Matrices?


---------------

ANSWER



In [84]:
import numpy as np
x=np.array([[1,2],
   [3,4]])
y=np.array([[5,6],
   [7,8]])
result = np.zeros((2,2), int)

for i in range(0,len(result)):
    for j in range(0,len(result[0])):
        for k in range(0,len(y)):
            result[i][j] += x[i][k]*y[k][j]

In [85]:
result

array([[19, 22],
       [43, 50]])

3- Write a Python Program to Transpose a Matrix?

----------------------

ANSWER

In [114]:
x = [[1,2],
    [3,4],
    [5,6]]

result = np.zeros((2,3), int)

for i in range(0, len(x)):
    for j in range(0,len(x[0])):
        result[j][i] = x[i][j]

print('transpose matrix of' )
for i in x:
    print(i)
print(f'\nis\n\n{result}')      

transpose matrix of
[1, 2]
[3, 4]
[5, 6]

is

[[1 3 5]
 [2 4 6]]


4- Write a Python Program to Sort Words in Alphabetic Order?


----------------------

ANSWER

In [119]:
words = input('enter a string: ')
new_word = words.split(' ')
new_word.sort()
for word in new_word:
    print(word, end=' ')

enter a string: hello world was the first python program
first hello program python the was world 

5 - Write a Python Program to Remove Punctuation From a String?

---------------

ANSWER

In [121]:
puncs = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

words = input('enter the string: ')

for word in words:
    if word in puncs:
        words = words.replace(word, '')
print(words)

enter the string: hello world!! this is a $ random string with & various punctuation marks%
hello world this is a  random string with  various punctuation marks
